#!/bin/bash

#
# QR Quick File Link
#
#  Quickly share files from your computer
#   using a QR code and a webserver.
#
# Author: tylersengia@gmail.com
#

#This is the directory of your webserver's html files. A temporary link will be placed here to link to the file you want to share.
WEB_DIR="/var/www/html/"

#This is the base URL of your webserver
HOST_URL="http://192.168.1.62/"

usage() {
cat << EOF
Usage:
	qrLinkFile FILE

Will create a temporary soft-link to the specified file in your webserver's directory, generate a QR code, and display the QR code to be scanned.
This script cleans up after itself, deleting the temporary files associated with it, so please do not hard-kill it!

NOTE: Please ensure that you have the proper permissions to access the webserver directory. You may have to use sudo!

Author: tylersengia@gmail.com
Github: https://github.com/ExpandingDev/QR-Quick-Linker
EOF
};

image_program=-1
found=0
function findImageProgram() {
    for var in "$@"; do
        if which $var &> /dev/null; then
            image_program=$var
	    found=1
        fi
    done
if [ $found -eq 0 ]
then
echo "Please install either eye-of-mate, eye-of-gnome or imagemajik!"
exit 1;
fi
}
findImageProgram display eog eom

if [ $# -eq 0 ]
then
echo "Not enough arguments given!"
usage
exit 1;
fi
#This is the basename of the temporary file that will be created. This really doesn't matter because we are adding a salt anyways
tmp_file="tmp-link"

#Thanks to: https://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash
filename=$(basename "$1")
extension="${filename##*.}"
filename="${1%.*}"

#We are adding a random salt to prevent browser caching.
salt=`base32 <(echo ${RANDOM:0:4})`

echo "File to link via QR and HTTP: $1"

#Create a soft-link from the target file to a temp file in the web server directory
ln $1 $WEB_DIR$salt$tmp_file.$extension

#Make a temporary QR code
qrencode -o tmp-qr.png "$HOST_URL$salt$tmp_file.$extension"

#Display the QR code using Eye of Mate
if [ "$image_program" == "eom" ]; then
eom -f tmp-qr.png
fi

if [ "$image_program" == "eog" ]; then
eog -f tmp-qr.png
fi

if [ "$image_program" == "display" ]; then
display tmp-qr.png
fi

#Remove our soft-link and the QR image
rm $WEB_DIR$salt$tmp_file.$extension
rm tmp-qr.png
